version: "3.9"

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.4
    command: ["--host","0.0.0.0","--port","8080","--scheme","http"]
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
  api:
    build:
      context: ./services/api
    container_name: rag_api
    restart: unless-stopped
    env_file:
      - ./services/api/.env
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    volumes:
      - ./services/api/app:/app/app
      - media_store:/app/media

volumes:
  weaviate_data:
  media_store: